language: node_js
node_js:
  - '8'
script: echo "========================"
script: echo "========================"
script: echo "=======  TEST  ========="
script: npm run test

script: echo "========================"
script: echo "========================"
script: echo "=======  BUILD  ========="
script: npm run build

script: echo "========================"
script: echo "========================"
script: echo "======  DEPLOY  ========"
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master

